[package]
name = "mlzutil"
description = "Various small utilities used at MLZ"
repository = "https://github.com/birkenfeld/mlzutil"
version = "0.1.1"
license = "MIT/Apache-2.0"
authors = ["Georg Brandl <g.brandl@fz-juelich.de>"]
documentation = "http://docs.rs/mlzutil"

[dependencies]
dns-lookup = "0.9.0"
hostname = "0.1.4"
itertools = "0.7.8"
time = "0.1.39"

interfaces = { version = "0.0.4", optional = true }
