[package]
name = "mlzutil"
version = "0.1.0"
license = "GPL-2.0+"
authors = ["Georg Brandl <g.brandl@fz-juelich.de>"]

[dependencies]
dns-lookup = "0.9.0"
hostname = "0.1.4"
interfaces = "0.0.4"
itertools = "0.7.8"
time = "0.1.39"
